config/routes.rb
Rails.application.routes.draw do

  root "dojos#index"

  resources :dojos do
      resources :students
    end

end

app/models/dojo.rb
class Dojo < ActiveRecord::Base
    validates :branch, :street, :city, :state, presence: true # check if all is included
    validates :state, length: { is: 2 } # check state is only 2 characters
    has_many :students # relations ALWAYS ADD
    before_validation :upper_state # before any other validations, check if state is upper case from method below
    def upper_state  # Method that checks if state is uppercase
        self.state.upcase!
    end
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :dojo
  validates :first_name, :last_name, :email, presence: true # check if all is included
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dojos_controller.rb
class DojosController < ApplicationController
  def index
  end

  def new
  end

  def create
    @dojo = Dojo.new(dojo_params)
    #Flash Vlidations
    if @dojo.valid?
      @dojo.save
      redirect_to "/"
    else
      flash[:error] = @dojo.errors.full_messages
      redirect_to "/dojos/new"
    end
  end

  def show
    @dojo = Dojo.find(params[:id])
    redirect_to "/dojos/#{params[:id]}/students" # redirects to the students page and basically merges the 2 html's together
  end

  def edit
    @dojo = Dojo.find(params[:id])
  end

  def update
    @dojo = Dojo.find(params[:id])
    @dojo.update(dojo_params)
    redirect_to "/"
  end

  def destroy
    @dojo = Dojo.find(params[:id])
    @dojo.destroy
    redirect_to "/"
  end

  def process_dojo_form
  end

  def set_dojo
  end

  private # dojo private dictionary!
  def dojo_params
    params.require(:dojo).permit(:branch, :street, :city, :state)
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :set_dojo, only: [:index, :new]

  def index
  end

  def new
  end

  def create
    student = Student.new(process_student_form)
    set_student_dojo(student)
    redirect_to dojo_students_url
  end

  def show
  end

  def edit
  end

  def update
    @student.update(process_student_form)
    set_student_dojo(@student)
    redirect_to dojo_student_url(@student.dojo.id, @student.id)
  end

  def destroy
    @student = Student.find(params[:id]).destroy
    redirect_to "/dojos/#{params[:id]}/students"
  end

  private
  def process_student_form
    params.require(:student).permit(:first_name, :last_name, :email)
  end

  def set_student_dojo student
    student.dojo = Dojo.find_by(branch: params[:student][:dojo])
    student.save
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def set_dojo
    @dojo = Dojo.find(params[:dojo_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dojos_helper.rb
module DojosHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/dojos/create.html.erb
<h1>Dojos#create</h1>
<p>Find me in app/views/dojos/create.html.erb</p>

app/views/dojos/destroy.html.erb
<h1>Dojos#destroy</h1>
<p>Find me in app/views/dojos/destroy.html.erb</p>

app/views/dojos/edit.html.erb
<h1>Editing <%= @dojo.branch %></h1>
<form action="/dojos/<%= @dojo.id %>" method="POST">
<input type="hidden" name="_method" value="patch">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<%# Show what is in said variables and give the change to change: NOTE The  "value=" part is what shows the already inputted info %> 
<p>Branch: <input type="text" name="dojo[branch]" value="<%= @dojo.branch %>"></p>
<p>Street: <input type="text" name="dojo[street]" value="<%= @dojo.street %>"></p>
<p>City: <input type="text" name="dojo[city]" value="<%= @dojo.city %>"></p>
<p>State: <input type="text" name="dojo[state]" value="<%= @dojo.state %>"></p>
<p><input type="submit" value="Update"></p>
</form>
<p><a href="/">Go Back</a></p>

app/views/dojos/index.html.erb
<div id="container">
<style>
    #container{
        background-color: grey;
    }
</style>
    <h1>Listing <%= Dojo.count %> Dojos</h1>
    <table>
        <thead>
            <tr>
                <th>Coding Dojo Branch</th>
                <th>Street</th>
                <th>City</th>
                <th>State</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <% Dojo.all.each do |d| %>
                <tr>
                    <td><%= d.branch %></td>
                    <td><%= d.street %></td>
                    <td><%= d.city %></td>
                    <td><%= d.state %></td>

                    <%# Show end routes %>
                    <td><a href="/dojos/<%= d.id %>">Show</a></td>
                    <td><a href="/dojos/<%= d.id %>/edit">Edit</a></td>
                    <td><a href="/dojos/<%= d.id %>" data-method="delete">Delete</a></td>
                </tr>   
            <% end %>
        </tbody>
    </table>
    <br>
    <p><a href="/dojos/new">Create New Dojo</a></p>
</div>

app/views/dojos/new.html.erb
<h1>Create A New Dojo:</h1>
<style>
.errorMsg{
    color: red;
}
</style>
<%# --------------Validation Flash:------------------- %>
<% if flash[:error] %>
    <% flash[:error].each do |msg| %>
        <p class="errorMsg"><%= msg %></p>
    <% end %>
<% end %>

<%# -----------------Form-------------------- %>
<form action="/dojos/create" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <p>Branch:<input type="text" name="dojo[branch]"></p>
    <p>Street:<input type="text" name="dojo[street]"></p>
    <p>City:<input type="text" name="dojo[city]"></p>
    <p>State:<input type="text" name="dojo[state]"></p>
    <p><input type="submit" value="Create"></p>
</form>

app/views/dojos/process_dojo_form.html.erb
<h1>Dojos#process_dojo_form</h1>
<p>Find me in app/views/dojos/process_dojo_form.html.erb</p>

app/views/dojos/set_dojo.html.erb
<h1>Dojos#set_dojo</h1>
<p>Find me in app/views/dojos/set_dojo.html.erb</p>

app/views/dojos/show.html.erb
<h1><%= @dojo.branch %></h1>
<p>Address: <%= @dojo.street %></p>
<p>City: <%= @dojo.city %></p>
<p>State: <%= @dojo.state %></p>
<p><a href="/">Go Back</a> | <a href="/dojos/<%= @dojo.id %>/edit">Edit</a></p>

app/views/dojos/update.html.erb
<h1>Dojos#update</h1>
<p>Find me in app/views/dojos/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DojoDashboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/destroy.html.erb
<h1>Students#destroy</h1>
<p>Find me in app/views/students/destroy.html.erb</p>

app/views/students/edit.html.erb
<h1>Editing <%= @student.first_name %> <%= @student.last_name %></h1>
<form action="<%= dojo_student_url(@student.dojo.id, @student.id) %>" method="POST">
    <input type="hidden" name="_method" value="patch">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <p>First Name: <input type="text" name="student[first_name]" value="<%= @student.first_name %>"></p>
    <p>Last Name: <input type="text" name="student[last_name]" value="<%= @student.last_name %>"></p>
    <p>Email Address: <input type="text" name="student[email]" value="<%= @student.email %>"></p>
    <p>Dojo: <select name="student[dojo]">
        <% Dojo.all.each do |d| %>
            <option <% if d == @student.dojo %>selected<% end %>><%= d.branch %></option>
        <% end %>
    </select></p>
    <p><input type="submit" value="Update"></p>
</form>
<p>test</p>
<p><a href="<%= dojo_url(@student.dojo.id) %>">Home</a> | <a href="<%= dojo_student_url(@student.dojo.id, @student.id) %>"><%= @student.first_name %></a></p>

app/views/students/index.html.erb
<h1><%= @dojo.branch %> Dojo</h1>
<p><a href="<%= edit_dojo_url(@dojo.id) %>">Edit</a></p>
<h3>Address: <%= @dojo.street %></h3>
<h3>City: <%= @dojo.city %></h3>
<h3>State: <%= @dojo.state %></h3>
<h2>Student Roster</h2>
<table>
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @dojo.students.each do |s| %>
            <tr>
                <td><%= s.first_name %></td>
                <td><%= s.last_name %></td>
                <td><%= s.email %></td>
                <td><a href="<%= dojo_student_url(@dojo.id, s.id) %>">Show</a> | <a href="<%= edit_dojo_student_url(@dojo.id, s.id) %>">Edit</a> | <a href="/dojos/<%= @dojo.id %>/students/<%= s.id %>" data-method="delete">Destroy</a></td>
            </tr>
        <% end %>
    </tbody>
<table>
<p>test 57675</p>
<p><a href="<%= dojos_url %>">Home</a> | <a href="<%= new_dojo_student_url %>">Add Student</a></p>

app/views/students/new.html.erb
<h1>New Student</h1>
<form action="<%= dojo_students_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <p>First Name: <input type="text" name="student[first_name]"></p>
    <p>Last Name: <input type="text" name="student[last_name]"></p>
    <p>Email Address: <input type="text" name="student[email]"></p>
    <p>Dojo: <select name="student[dojo]">
        <% Dojo.all.each do |d| %>
            <option <% if d == @dojo %>selected<% end %>><%= d.branch %></option>
        <% end %>
    </select></p>
    <p><input type="submit" value="Create"></p>
</form>
<p>test</p>
<p><a href="/dojos">Home</a> | <a href="<%= dojo_url(@dojo.id) %>"><%= @dojo.branch %></a></p>

app/views/students/show.html.erb
<h1><%= @student.dojo.branch %>'s <%= @student.first_name %> <%= @student.last_name %></h1>
<p>Email: <%= @student.email %>
<h2>Cohort</h2>
<table>
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        <% @student.dojo.students.where(created_at: (@student.created_at.beginning_of_day..@student.created_at.end_of_day)).where.not(id: @student.id).each do |s| %>
            <tr>
                <td><%= s.first_name %></td>
                <td><%= s.last_name %></td>
                <td><%= s.email %></td>
            </tr>
        <% end %>
    </tbody>
<table>
<p>test</p>
<p><a href="<%= dojo_url(@student.dojo.id) %>">Home</a> | <a href="<%= edit_dojo_student_url(@student.dojo.id, @student.id) %>">Edit</a></p>

app/views/students/update.html.erb
<h1>Students#update</h1>
<p>Find me in app/views/students/update.html.erb</p>